import { NextResponse } from "next/server"
import dbConnect from "@/lib/mongodb"
import Payment from "@/models/Payment"

export async function GET() {
  try {
    await dbConnect()

    // Get current month's payments
    const currentDate = new Date()
    const firstDayOfMonth = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1)
    const lastDayOfMonth = new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 0)

    const payments = await Payment.find({
      createdAt: { $gte: firstDayOfMonth, $lte: lastDayOfMonth },
    }).populate("Patient_ID", "FirstName LastName")

    // Generate text report
    let report = `NEWHOPE HOSPITAL - PAYMENTS REPORT\n`
    report += `Generated: ${new Date().toLocaleString()}\n`
    report += `Month: ${currentDate.toLocaleString("default", { month: "long", year: "numeric" })}\n`
    report += `${"=".repeat(50)}\n\n`

    let totalRevenue = 0
    let totalAdvance = 0
    let pendingCount = 0

    payments.forEach((payment: any, index: number) => {
      const patient = payment.Patient_ID
      report += `${index + 1}. Patient: ${patient?.FirstName || "Unknown"} ${patient?.LastName || ""}\n`
      report += `   Total Bill: ₦${payment.TotalBill.toLocaleString()}\n`
      report += `   Advance: ₦${payment.AdvancePayment.toLocaleString()}\n`
      report += `   Final Payment: ₦${payment.FinalPayment.toLocaleString()}\n`
      report += `   Method: ${payment.PaymentMethod}\n`
      report += `   Status: ${payment.PaymentStatus}\n`
      report += `   Date: ${payment.createdAt.toLocaleDateString()}\n\n`

      totalRevenue += payment.TotalBill
      totalAdvance += payment.AdvancePayment
      if (payment.PaymentStatus === "Pending") pendingCount++
    })

    report += `SUMMARY\n`
    report += `${"-".repeat(20)}\n`
    report += `Total Payments: ${payments.length}\n`
    report += `Total Revenue: ₦${totalRevenue.toLocaleString()}\n`
    report += `Total Advance: ₦${totalAdvance.toLocaleString()}\n`
    report += `Pending Payments: ${pendingCount}\n\n`
    report += `Report generated by NewHope Hospital Management System`

    return new NextResponse(report, {
      headers: {
        "Content-Type": "text/plain",
        "Content-Disposition": `attachment; filename="payments-report-${currentDate.toISOString().split("T")[0]}.txt"`,
      },
    })
  } catch (error) {
    return NextResponse.json({ message: "Error generating payments report" }, { status: 500 })
  }
}
