import { NextResponse } from "next/server"
import dbConnect from "@/lib/mongodb"
import Doctor from "@/models/Doctor"

export async function GET() {
  try {
    await dbConnect()

    // Get current month's doctors
    const currentDate = new Date()
    const firstDayOfMonth = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1)

    const doctors = await Doctor.find({
      createdAt: { $gte: firstDayOfMonth },
    }).populate("Ward_ID", "WardName")

    // Generate text report
    let report = `NEWHOPE HOSPITAL - DOCTORS REPORT\n`
    report += `Generated: ${new Date().toLocaleString()}\n`
    report += `Month: ${currentDate.toLocaleString("default", { month: "long", year: "numeric" })}\n`
    report += `${"=".repeat(50)}\n\n`

    // Group by ward
    const doctorsByWard = doctors.reduce((acc: any, doctor: any) => {
      const wardName = doctor.Ward_ID?.WardName || "Unassigned"
      if (!acc[wardName]) acc[wardName] = []
      acc[wardName].push(doctor)
      return acc
    }, {})

    Object.entries(doctorsByWard).forEach(([wardName, wardDoctors]: [string, any]) => {
      report += `WARD: ${wardName}\n`
      report += `${"-".repeat(20)}\n`
      wardDoctors.forEach((doctor: any, index: number) => {
        report += `${index + 1}. Dr. ${doctor.FirstName} ${doctor.LastName}\n`
        report += `   Phone: ${doctor.Phone_Num}\n`
        report += `   Type: ${doctor.Employment_Type}\n\n`
      })
    })

    report += `\nTotal Doctors: ${doctors.length}\n`
    report += `Report generated by NewHope Hospital Management System`

    return new NextResponse(report, {
      headers: {
        "Content-Type": "text/plain",
        "Content-Disposition": `attachment; filename="doctors-report-${currentDate.toISOString().split("T")[0]}.txt"`,
      },
    })
  } catch (error) {
    return NextResponse.json({ message: "Error generating doctors report" }, { status: 500 })
  }
}
