// Nigerian patient seed data matching the Patient schema
// All fields are included and names are full Nigerian names

module.exports = [
  {
    FirstName: "John",
    LastName: "Okafor",
    Phone_Num: "+2344544544533",
    Address: "Taiwo Street, Lagos",
    Height: 175,
    Weight: 70,
    Age: 32,
    Gender: "Male",
    Blood_Grp: "A+",
    Admit_Date: "2025-06-01",
    Status: "Admitted",
    Treatment_Type: "Malaria Treatment",
  },
  {
    FirstName: "Peter",
    LastName: "Adebayo",
    Phone_Num: "+2344544645654",
    Address: "Oba Street, Ibadan",
    Height: 155,
    Weight: 75,
    Age: 28,
    Gender: "Male",
    Blood_Grp: "O+",
    Admit_Date: "2025-06-02",
    Status: "Admitted",
    Treatment_Type: "Typhoid Fever",

  },
  {
    FirstName: "James",
    LastName: "Eze",
    Phone_Num: "+2343246760987",
    Address: "Akindele Street, Enugu",
    Height: 175,
    Weight: 74,
    Age: 40,
    Gender: "Male",
    Blood_Grp: "B+",
    Admit_Date: "2025-06-03",
    Status: "Admitted",
    Treatment_Type: "Appendicitis Surgery",

  },
  {
    FirstName: "Joshua",
    LastName: "Ogunleye",
    Phone_Num: "+2341234544873",
    Address: "Bajimo Street, Abeokuta",
    Height: 155,
    Weight: 60,
    Age: 36,
    Gender: "Male",
    Blood_Grp: "AB+",
    Admit_Date: "2025-06-04",
    Status: "Admitted",
    Treatment_Type: "Asthma Management",

  },
  {
    FirstName: "Kennedy",
    LastName: "Nwankwo",
    Phone_Num: "+2346777144533",
    Address: "Adebiyi Street, Port Harcourt",
    Height: 174,
    Weight: 71,
    Age: 29,
    Gender: "Male",
    Blood_Grp: "O-",
    Admit_Date: "2025-06-05",
    Status: "Admitted",
    Treatment_Type: "Diabetes Care",
  },
  {
    FirstName: "Chinedu",
    LastName: "Mba",
    Phone_Num: "+2344547773433",
    Address: "Oriade Street, Onitsha",
    Height: 155,
    Weight: 78,
    Age: 34,
    Gender: "Male",
    Blood_Grp: "A-",
    Admit_Date: "2025-06-06",
    Status: "Admitted",
    Treatment_Type: "Hypertension",

  },
  {
    FirstName: "Ifeanyi",
    LastName: "Okoro",
    Phone_Num: "+2342226704333",
    Address: "Prosperity Street, Owerri",
    Height: 172,
    Weight: 73,
    Age: 27,
    Gender: "Male",
    Blood_Grp: "B-",
    Admit_Date: "2025-06-07",
    Status: "Admitted",
    Treatment_Type: "Ulcer Treatment",

  },
  {
    FirstName: "Precious",
    LastName: "Akinyemi",
    Phone_Num: "+2343340544123",
    Address: "Benson Street, Ilorin",
    Height: 175,
    Weight: 70,
    Age: 25,
    Gender: "Female",
    Blood_Grp: "AB-",
    Admit_Date: "2025-06-08",
    Status: "Admitted",
    Treatment_Type: "Maternity Care",

  },
  {
    FirstName: "Angel",
    LastName: "Ojo",
    Phone_Num: "+2343334544663",
    Address: "Adeleye Street, Akure",
    Height: 155,
    Weight: 60,
    Age: 31,
    Gender: "Female",
    Blood_Grp: "O+",
    Admit_Date: "2025-06-09",
    Status: "Admitted",
    Treatment_Type: "Sickle Cell Management",

  },
  {
    FirstName: "Temi",
    LastName: "Adewale",
    Phone_Num: "+2340987548773",
    Address: "Akinbolu Street, Ibadan",
    Height: 175,
    Weight: 70,
    Age: 22,
    Gender: "Female",
    Blood_Grp: "A+",
    Admit_Date: "2025-06-10",
    Status: "Admitted",
    Treatment_Type: "General Checkup",

  },
  {
    FirstName: "Tochukwu",
    LastName: "Ezeani",
    Phone_Num: "+2344543349933",
    Address: "Kehinde Street, Nsukka",
    Height: 185,
    Weight: 50,
    Age: 30,
    Gender: "Male",
    Blood_Grp: "B+",
    Admit_Date: "2025-06-11",
    Status: "Admitted",
    Treatment_Type: "Hernia Surgery",

  },
  {
    FirstName: "Kunle",
    LastName: "Ogunbanjo",
    Phone_Num: "+2342504340003",
    Address: "Yusuf Street, Kaduna",
    Height: 185,
    Weight: 79,
    Age: 38,
    Gender: "Male",
    Blood_Grp: "O-",
    Admit_Date: "2025-06-12",
    Status: "Admitted",
    Treatment_Type: "Kidney Stone Removal",

  },
  {
    FirstName: "Teniola",
    LastName: "Balogun",
    Phone_Num: "+2344545551113",
    Address: "Tunde Street, Lagos",
    Height: 175,
    Weight: 70,
    Age: 26,
    Gender: "Female",
    Blood_Grp: "A-",
    Admit_Date: "2025-06-13",
    Status: "Admitted",
    Treatment_Type: "ENT Surgery",

  },
  {
    FirstName: "Ayo",
    LastName: "Olowu",
    Phone_Num: "+2344531140000",
    Address: "Alaba Street, Lagos",
    Height: 166,
    Weight: 80,
    Age: 35,
    Gender: "Male",
    Blood_Grp: "B+",
    Admit_Date: "2025-06-14",
    Status: "Admitted",
    Treatment_Type: "Orthopedic Care",

  },
  {
    FirstName: "Daniel",
    LastName: "Okon",
    Phone_Num: "+2342224543333",
    Address: "Odunfin Street, Benin",
    Height: 175,
    Weight: 70,
    Age: 33,
    Gender: "Male",
    Blood_Grp: "O+",
    Admit_Date: "2025-06-15",
    Status: "Admitted",
    Treatment_Type: "Eye Surgery",

  },
]
