// Nigerian hospital payment seed data matching the Payment schema
// Expanded to 8x the base dataset with distinct references

const basePayments = [
  {
    Patient_ID: null,
    TotalBill: 150000,
    AdvancePayment: 50000,
    FinalPayment: 100000,
    PaymentMethod: "Cash",
    PaymentStatus: "Paid",
  },
  {
    Patient_ID: null,
    TotalBill: 75000,
    AdvancePayment: 25000,
    FinalPayment: 50000,
    PaymentMethod: "Bank_Transfer",
    PaymentStatus: "Pending",
  },
  {
    Patient_ID: null,
    TotalBill: 300000,
    AdvancePayment: 100000,
    FinalPayment: 200000,
    PaymentMethod: "Credit_Card",
    PaymentStatus: "Paid",
    CC_Num: "4532-1234-5678-9012",
    CardHoldersName: "Ibrahim Musa",
  },
  {
    Patient_ID: null,
    TotalBill: 200000,
    AdvancePayment: 80000,
    FinalPayment: 120000,
    PaymentMethod: "Check",
    PaymentStatus: "Pending",
    Check_Num: "CHK001234",
  },
  {
    Patient_ID: null,
    TotalBill: 120000,
    AdvancePayment: 40000,
    FinalPayment: 80000,
    PaymentMethod: "Cash",
    PaymentStatus: "Paid",
  },
  {
    Patient_ID: null,
    TotalBill: 90000,
    AdvancePayment: 30000,
    FinalPayment: 60000,
    PaymentMethod: "Bank_Transfer",
    PaymentStatus: "Pending",
  },
  {
    Patient_ID: null,
    TotalBill: 180000,
    AdvancePayment: 60000,
    FinalPayment: 120000,
    PaymentMethod: "Credit_Card",
    PaymentStatus: "Paid",
    CC_Num: "4532-5678-1234-9012",
    CardHoldersName: "Blessing Okonkwo",
  },
  {
    Patient_ID: null,
    TotalBill: 220000,
    AdvancePayment: 100000,
    FinalPayment: 120000,
    PaymentMethod: "Check",
    PaymentStatus: "Pending",
    Check_Num: "CHK009876",
  },
  {
    Patient_ID: null,
    TotalBill: 110000,
    AdvancePayment: 40000,
    FinalPayment: 70000,
    PaymentMethod: "Cash",
    PaymentStatus: "Paid",
  },
  {
    Patient_ID: null,
    TotalBill: 95000,
    AdvancePayment: 35000,
    FinalPayment: 60000,
    PaymentMethod: "Bank_Transfer",
    PaymentStatus: "Pending",
  },
]

module.exports = Array.from({ length: 8 }, (_, batchIndex) =>
  basePayments.map((payment, paymentIndex) => ({
    ...payment,
    TotalBill: payment.TotalBill + batchIndex * 5000 + paymentIndex * 1000,
    AdvancePayment: payment.AdvancePayment + batchIndex * 2000,
    FinalPayment: payment.TotalBill + batchIndex * 5000 + paymentIndex * 1000 - (payment.AdvancePayment + batchIndex * 2000),
    CC_Num: payment.CC_Num ? `${payment.CC_Num}-${batchIndex + 1}` : payment.CC_Num,
    CardHoldersName: payment.CardHoldersName ? `${payment.CardHoldersName} ${batchIndex + 1}` : payment.CardHoldersName,
    Check_Num: payment.Check_Num ? `${payment.Check_Num}-${batchIndex + 1}` : payment.Check_Num,
  })),
).flat()
